name: Build and Publish Profiles

on:
  schedule:
    - cron: "0 22 * * *" # Ежедневно в 22:00
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish Profiles
    runs-on: ubuntu-latest

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=profiles" >> $GITHUB_ENV
          echo "TAG_NAME=profiles" >> $GITHUB_ENV
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Profiles
        run: |
          mkdir -p ./publish
          # Генерация файлов профилей
          echo "# Example Profile 1" > ./publish/profile1.txt
          echo "*://*.example1.com/*" >> ./publish/profile1.txt

          echo "# Example Profile 2" > ./publish/profile2.txt
          echo "*://*.example2.com/*" >> ./publish/profile2.txt
        shell: bash

      - name: Upload files to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            ./publish/profile1.txt
            ./publish/profile2.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
